site_name: mlky
repo_name: jammont/mlky
repo_url: https://github.com/jammont/mlky
docs_dir: docs/
theme:
  name: readthedocs
plugins:
  - search:
  - mkapi:
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: numpy

nav:
  - Home: index.md
  - Getting Started: usage.md
  # - Definitions: defs.md
  - API: $api/mlky.***
