site_name: mlky
repo_name: jammont/mlky
repo_url: https://github.com/jammont/mlky
docs_dir: docs/
theme:
  name: material
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - "Getting Started": usage.md
  - "api/configs/Config": api/config.md
  - "api/configs/Sect": api/sect.md
  - "api/configs/Var": api/var.md
  - "api/configs/funcs": api/funcs.md
  - "api/configs/magics": api/magics.md
  - "api/utils/formatters": api/formatters.md
  - "api/utils/io": api/io.md
  - "api/utils/prettyslice": api/prettyslice.md
  - "api/utils/templates": api/templates.md
