"""
Stores useful templates
"""


yamlHeader = """\
# This file was generated by mlky
# Usage: --config [this file].yml --patch "generated" --defs definitions.yml
#
# mlky uses special syntax ${?key} to perform value replacement operations at runtime:
#   ${.key} = Replace this ${} in the string with the value at config[key]
#   ${$key} = Replace this ${} in the string with the environment variable `key`
#   ${?key} = Replace this ${} in the string with the str(return) from function `key` in the registered functions
#   ${!key} = Replace this value with the return from function `key` in the registered functions
#
# Additionally, mlky enables special keys for certain types:
#         \ = mlky.Null, this is equivalent to deleting the key from the config altogether
#
# The "K" column is the key column indicating what type of key this is:
#         ! = This key is required to be manually set
#         ? = This is an optional key under a required section
#   <blank> = Fully optional, can remove from config with no repercussions

"""
